# Generated by Django 3.0.5 on 2020-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='artist',
            field=models.CharField(max_length=100, verbose_name='Artist/band'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='lyrics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Song title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Submitted by'),
        ),
    ]
